package com.example.tracstock.domain.model

data class CompanyOverview(
    val symbol: String,
    val assetType: String,
    val name: String,
    val description: String,
    val cik: String,
    val exchange: String,
    val currency: String, // Already here, directly maps from API for consistency
    val country: String,
    val sector: String,
    val industry: String,
    val address: String,
    val fiscalYearEnd: String,
    val latestQuarter: String,
    val marketCapitalization: String,
    val ebitda: String,
    val peRatio: String,
    val pegRatio: String,
    val bookValue: String,
    val dividendYield: String,
    val eps: String,
    val revenuePerShareTTM: String,
    val profitMargin: String,
    val operatingMarginTTM: String,
    val returnOnAssetsTTM: String,
    val returnOnEquityTTM: String,
    val revenueTTM: String,
    val grossProfitTTM: String,
    val dilutedEPSTTM: String,
    val quarterlyEarningsGrowthYOY: String,
    val quarterlyRevenueGrowthYOY: String,
    val analystTargetPrice: String,
    val trailingPE: String,
    val forwardPE: String,
    val priceToSalesRatioTTM: String,
    val priceToBookRatio: String,
    val evToRevenue: String,
    val evToEBITDA: String,
    val beta: String,
    val high52Week: String,
    val low52Week: String,
    val movingAverage50Day: String,
    val movingAverage200Day: String,
    val sharesOutstanding: String,
    val dividendDate: String,
    val exDividendDate: String
)

